### PR TITLE
fix: null in yml files

### LINKED ISSUE #8: Prevent `null`s in yml
https://github.com/typescord/mrm-preset/blob/86dc4b1369b7401f1978977517426c3f79080a4c/src/ci/index.ts#L69-L70
These lines can actually produce `null` in the final YML.

### PR DESCRIPTION
**Pull request by Aakodal**
It works, but I'm not proud of it, especially because of the `any`.

Fixes #8.

### CODE REVIEW

**Review by Mesteery — CHANGES_REQUESTED** [review]
Can you also bump this ? (For Node.js 16)

File: src/ci/index.ts [hunk 1]
```diff
@@ -1,7 +1,7 @@
 import { packageJson, yaml } from 'mrm-core';
 import { minVersion, satisfies } from 'semver';
 
-import { format, isUsingYarn } from '../utils';
+import { cleanObject, format, isUsingYarn } from '../utils';
 
 const NODE_MAJOR_VERSIONS = Array.from({ length: 15 }, (_, index) => (index + 1).toString());
```
Comment (Mesteery) [inline src/ci/index.ts]:
```suggestion
const NODE_MAJOR_VERSIONS = Array.from({ length: 16 }, (_, index) => (index + 1).toString());
```

**Review by Mesteery — APPROVED** [review]
LGTM
